#!/command/with-contenv bash

mkdir -p /opt/scrutiny/influxdb/

if [ -f "/opt/scrutiny/influxdb/config.yaml" ]; then
    echo "influxdb config file already exists. skipping."
else
cat << 'EOF' > /opt/scrutiny/influxdb/config.yaml
bolt-path: /opt/scrutiny/influxdb/influxd.bolt
engine-path: /opt/scrutiny/influxdb/engine
http-bind-address: ":8086"
reporting-disabled: true
EOF
fi

echo "starting influxdb"
exec influxd run
