#!/usr/bin/env bash

SEMVER_TAG_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$'

GIT_TAG="$(git describe --tags --exact-match 2>/dev/null)"

if [[ "${GIT_TAG}" =~ ${SEMVER_TAG_REGEX} ]]; then
    echo "generating version file from the checked out release tag"
    VERSION_INFO="${GIT_TAG}"
else
    if [[ -n "${GIT_TAG}" ]]; then
        echo "ignoring tag ${GIT_TAG}, it is not a release version"
    fi

    GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    if [[ "${GIT_BRANCH}" == "HEAD" ]]; then
        # detached at an untagged commit, so git has no name for it
        GIT_BRANCH="${GITHUB_REF_NAME:-detached}"
    fi

    echo "no release tag on the checked out commit, generating version file from the branch"
    VERSION_INFO="${GIT_BRANCH}#$(git rev-parse --short=7 HEAD)"
fi

echo "writing version file (version: ${VERSION_INFO})"
cat <<EOT > src/environments/versions.ts
// this file is automatically generated by git.version.ts script
export const versionInfo = {
    version: '${VERSION_INFO}',
};
EOT
