#!/usr/bin/with-contenv bash

# Should be kept in sync with init-collector.sh

# Create placeholder collector.yaml file if not provided by user
if [ ! -f "/scrutiny/jobber/jobber.yaml" ]; then
    touch /scrutiny/config/collector.yaml
fi

echo "populating jobber config"
confd -onetime -backend file -file /scrutiny/config/collector.yaml

echo "starting jobber"
mkdir -p /var/jobber/0/
su -c "/usr/lib/x86_64-linux-gnu/jobberrunner -u /var/jobber/0/cmd.sock /scrutiny/jobber/jobber.yaml" root
