// Code generated by MockGen. DO NOT EDIT.
// Source: webapp/backend/pkg/database/interface.go

// Package mock_database is a generated GoMock package.
package mock_database

import (
	context "context"
	reflect "reflect"

	pkg "github.com/analogj/scrutiny/webapp/backend/pkg"
	models "github.com/analogj/scrutiny/webapp/backend/pkg/models"
	collector "github.com/analogj/scrutiny/webapp/backend/pkg/models/collector"
	measurements "github.com/analogj/scrutiny/webapp/backend/pkg/models/measurements"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceRepo is a mock of DeviceRepo interface.
type MockDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepoMockRecorder
}

// MockDeviceRepoMockRecorder is the mock recorder for MockDeviceRepo.
type MockDeviceRepoMockRecorder struct {
	mock *MockDeviceRepo
}

// NewMockDeviceRepo creates a new mock instance.
func NewMockDeviceRepo(ctrl *gomock.Controller) *MockDeviceRepo {
	mock := &MockDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepo) EXPECT() *MockDeviceRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDeviceRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeviceRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeviceRepo)(nil).Close))
}

// DeleteDevice mocks base method.
func (m *MockDeviceRepo) DeleteDevice(ctx context.Context, wwn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, wwn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDeviceRepoMockRecorder) DeleteDevice(ctx, wwn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteDevice), ctx, wwn)
}

// DeleteZFSPool mocks base method.
func (m *MockDeviceRepo) DeleteZFSPool(ctx context.Context, guid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZFSPool", ctx, guid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteZFSPool indicates an expected call of DeleteZFSPool.
func (mr *MockDeviceRepoMockRecorder) DeleteZFSPool(ctx, guid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZFSPool", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteZFSPool), ctx, guid)
}

// GetDeviceDetails mocks base method.
func (m *MockDeviceRepo) GetDeviceDetails(ctx context.Context, wwn string) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDetails", ctx, wwn)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDetails indicates an expected call of GetDeviceDetails.
func (mr *MockDeviceRepoMockRecorder) GetDeviceDetails(ctx, wwn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDetails", reflect.TypeOf((*MockDeviceRepo)(nil).GetDeviceDetails), ctx, wwn)
}

// GetDevices mocks base method.
func (m *MockDeviceRepo) GetDevices(ctx context.Context) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockDeviceRepoMockRecorder) GetDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockDeviceRepo)(nil).GetDevices), ctx)
}

// GetSmartAttributeHistory mocks base method.
func (m *MockDeviceRepo) GetSmartAttributeHistory(ctx context.Context, wwn, durationKey string, selectEntries, selectEntriesOffset int, attributes []string) ([]measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartAttributeHistory", ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes)
	ret0, _ := ret[0].([]measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartAttributeHistory indicates an expected call of GetSmartAttributeHistory.
func (mr *MockDeviceRepoMockRecorder) GetSmartAttributeHistory(ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartAttributeHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetSmartAttributeHistory), ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes)
}

// GetSmartTemperatureHistory mocks base method.
func (m *MockDeviceRepo) GetSmartTemperatureHistory(ctx context.Context, durationKey string) (map[string][]measurements.SmartTemperature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartTemperatureHistory", ctx, durationKey)
	ret0, _ := ret[0].(map[string][]measurements.SmartTemperature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartTemperatureHistory indicates an expected call of GetSmartTemperatureHistory.
func (mr *MockDeviceRepoMockRecorder) GetSmartTemperatureHistory(ctx, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartTemperatureHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetSmartTemperatureHistory), ctx, durationKey)
}

// GetSummary mocks base method.
func (m *MockDeviceRepo) GetSummary(ctx context.Context) (map[string]*models.DeviceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx)
	ret0, _ := ret[0].(map[string]*models.DeviceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockDeviceRepoMockRecorder) GetSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetSummary), ctx)
}

// GetZFSPoolDetails mocks base method.
func (m *MockDeviceRepo) GetZFSPoolDetails(ctx context.Context, guid string) (models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolDetails", ctx, guid)
	ret0, _ := ret[0].(models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolDetails indicates an expected call of GetZFSPoolDetails.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolDetails(ctx, guid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolDetails", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolDetails), ctx, guid)
}

// GetZFSPoolMetricsHistory mocks base method.
func (m *MockDeviceRepo) GetZFSPoolMetricsHistory(ctx context.Context, guid, durationKey string) ([]measurements.ZFSPoolMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolMetricsHistory", ctx, guid, durationKey)
	ret0, _ := ret[0].([]measurements.ZFSPoolMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolMetricsHistory indicates an expected call of GetZFSPoolMetricsHistory.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolMetricsHistory(ctx, guid, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolMetricsHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolMetricsHistory), ctx, guid, durationKey)
}

// GetZFSPools mocks base method.
func (m *MockDeviceRepo) GetZFSPools(ctx context.Context) ([]models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPools", ctx)
	ret0, _ := ret[0].([]models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPools indicates an expected call of GetZFSPools.
func (mr *MockDeviceRepoMockRecorder) GetZFSPools(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPools", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPools), ctx)
}

// GetZFSPoolsSummary mocks base method.
func (m *MockDeviceRepo) GetZFSPoolsSummary(ctx context.Context) (map[string]*models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolsSummary", ctx)
	ret0, _ := ret[0].(map[string]*models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolsSummary indicates an expected call of GetZFSPoolsSummary.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolsSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolsSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolsSummary), ctx)
}

// HealthCheck mocks base method.
func (m *MockDeviceRepo) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockDeviceRepoMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockDeviceRepo)(nil).HealthCheck), ctx)
}

// LoadSettings mocks base method.
func (m *MockDeviceRepo) LoadSettings(ctx context.Context) (*models.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSettings", ctx)
	ret0, _ := ret[0].(*models.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSettings indicates an expected call of LoadSettings.
func (mr *MockDeviceRepoMockRecorder) LoadSettings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSettings", reflect.TypeOf((*MockDeviceRepo)(nil).LoadSettings), ctx)
}

// RegisterDevice mocks base method.
func (m *MockDeviceRepo) RegisterDevice(ctx context.Context, dev models.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDevice", ctx, dev)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterDevice indicates an expected call of RegisterDevice.
func (mr *MockDeviceRepoMockRecorder) RegisterDevice(ctx, dev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDevice", reflect.TypeOf((*MockDeviceRepo)(nil).RegisterDevice), ctx, dev)
}

// RegisterZFSPool mocks base method.
func (m *MockDeviceRepo) RegisterZFSPool(ctx context.Context, pool models.ZFSPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterZFSPool", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterZFSPool indicates an expected call of RegisterZFSPool.
func (mr *MockDeviceRepoMockRecorder) RegisterZFSPool(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterZFSPool", reflect.TypeOf((*MockDeviceRepo)(nil).RegisterZFSPool), ctx, pool)
}

// SaveSettings mocks base method.
func (m *MockDeviceRepo) SaveSettings(ctx context.Context, settings models.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSettings indicates an expected call of SaveSettings.
func (mr *MockDeviceRepoMockRecorder) SaveSettings(ctx, settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSettings", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSettings), ctx, settings)
}

// SaveSmartAttributes mocks base method.
func (m *MockDeviceRepo) SaveSmartAttributes(ctx context.Context, wwn string, collectorSmartData collector.SmartInfo) (measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSmartAttributes", ctx, wwn, collectorSmartData)
	ret0, _ := ret[0].(measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSmartAttributes indicates an expected call of SaveSmartAttributes.
func (mr *MockDeviceRepoMockRecorder) SaveSmartAttributes(ctx, wwn, collectorSmartData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSmartAttributes", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSmartAttributes), ctx, wwn, collectorSmartData)
}

// SaveSmartTemperature mocks base method.
func (m *MockDeviceRepo) SaveSmartTemperature(ctx context.Context, wwn, deviceProtocol string, collectorSmartData collector.SmartInfo, retrieveSCTTemperatureHistory bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSmartTemperature", ctx, wwn, deviceProtocol, collectorSmartData, retrieveSCTTemperatureHistory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSmartTemperature indicates an expected call of SaveSmartTemperature.
func (mr *MockDeviceRepoMockRecorder) SaveSmartTemperature(ctx, wwn, deviceProtocol, collectorSmartData, retrieveSCTTemperatureHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSmartTemperature", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSmartTemperature), ctx, wwn, deviceProtocol, collectorSmartData, retrieveSCTTemperatureHistory)
}

// SaveZFSPoolMetrics mocks base method.
func (m *MockDeviceRepo) SaveZFSPoolMetrics(ctx context.Context, pool models.ZFSPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveZFSPoolMetrics", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveZFSPoolMetrics indicates an expected call of SaveZFSPoolMetrics.
func (mr *MockDeviceRepoMockRecorder) SaveZFSPoolMetrics(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveZFSPoolMetrics", reflect.TypeOf((*MockDeviceRepo)(nil).SaveZFSPoolMetrics), ctx, pool)
}

// UpdateDevice mocks base method.
func (m *MockDeviceRepo) UpdateDevice(ctx context.Context, wwn string, collectorSmartData collector.SmartInfo) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, wwn, collectorSmartData)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockDeviceRepoMockRecorder) UpdateDevice(ctx, wwn, collectorSmartData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDevice), ctx, wwn, collectorSmartData)
}

// UpdateDeviceArchived mocks base method.
func (m *MockDeviceRepo) UpdateDeviceArchived(ctx context.Context, wwn string, archived bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceArchived", ctx, wwn, archived)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceArchived indicates an expected call of UpdateDeviceArchived.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceArchived(ctx, wwn, archived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceArchived", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceArchived), ctx, wwn, archived)
}

// UpdateDeviceLabel mocks base method.
func (m *MockDeviceRepo) UpdateDeviceLabel(ctx context.Context, wwn, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceLabel", ctx, wwn, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceLabel indicates an expected call of UpdateDeviceLabel.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceLabel(ctx, wwn, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceLabel", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceLabel), ctx, wwn, label)
}

// UpdateDeviceMuted mocks base method.
func (m *MockDeviceRepo) UpdateDeviceMuted(ctx context.Context, wwn string, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceMuted", ctx, wwn, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceMuted indicates an expected call of UpdateDeviceMuted.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceMuted(ctx, wwn, muted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceMuted", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceMuted), ctx, wwn, muted)
}

// UpdateDeviceStatus mocks base method.
func (m *MockDeviceRepo) UpdateDeviceStatus(ctx context.Context, wwn string, status pkg.DeviceStatus) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceStatus", ctx, wwn, status)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceStatus indicates an expected call of UpdateDeviceStatus.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceStatus(ctx, wwn, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceStatus", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceStatus), ctx, wwn, status)
}

// UpdateZFSPoolArchived mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolArchived(ctx context.Context, guid string, archived bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolArchived", ctx, guid, archived)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolArchived indicates an expected call of UpdateZFSPoolArchived.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolArchived(ctx, guid, archived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolArchived", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolArchived), ctx, guid, archived)
}

// UpdateZFSPoolLabel mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolLabel(ctx context.Context, guid, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolLabel", ctx, guid, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolLabel indicates an expected call of UpdateZFSPoolLabel.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolLabel(ctx, guid, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolLabel", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolLabel), ctx, guid, label)
}

// UpdateZFSPoolMuted mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolMuted(ctx context.Context, guid string, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolMuted", ctx, guid, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolMuted indicates an expected call of UpdateZFSPoolMuted.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolMuted(ctx, guid, muted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolMuted", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolMuted), ctx, guid, muted)
}
